### ISSUE TITLE
[리팩토링]

### ISSUE THREAD

**Issue by juo1221** [juo1221/inf-assign#10]
### Todo
- [x] 폰트 preload 적용
- [x] 스켈레톤 UI 적용
- [x] 대체 이미지 설정
- [x] 로딩스피너 추가
- [x] 하드코딩 제거
