### ISSUE TITLE
메인 페이지 스타일링

### ISSUE THREAD

**Issue by juo1221** [juo1221/inf-assign#4]
### Todo
- [x] 검색바 스타일링
- [x] 강의 리스트 스타일링
- [x]  검색 결과 스타일링
- [x] plus 버튼 스타일링
- [x] 모달창 스타일링
- [x] 검색바 border-radius 애니메이션 효과적용
- [x] 상세페이지 스타일링
- [x] 폰트 적용
